export const admin ="/admin"
export const adminUser ="/admin/users"
export const adminLines ="/admin/lines"
export const adminDesing ="/admin/designs"
export const adminSublines ="/admin/sublines"
export const adminProducts ="/admin/products"
export const adminItemProduct ="/admin/:id"
export const nuestrosDisenios ="/nuestros-disenios"
export const nuestraHistoria ="/nuestra-historia"
export const nuestraCreadora ="/nuestra-creadora"
export const zonaOutlet ="/zona-outlet"
export const muroFama ="/muro-fama"
export const productClient="/products"
export const routeFacebook ="https://www.facebook.com/famdc32008"
export const routeInstagram ="https://www.instagram.com/mammamiaviena/"


